name: 01-trigger-azure-cast-scan-pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  CastScanning:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.5.0]
    steps:
      - name: Azure pipelines actions
        uses: Azure/pipelines@v3.0-node20
        with: 
         azure-devops-project-url: 'https://dev.azure.com/rvmado/NVS_EH'
         azure-pipeline-name: 'Application03'
         azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
       # runs:
        #  using: 'node20'
        #  main: 'main.js'
