name: 01-trigger-azure-cast-scan-pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  NodeJS:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.5.0]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm cache clean --force
    - run: npm install npm@latest -g
    
  CastScanning:
     runs-on: ubuntu-latest
     steps:
        - name: Azure pipelines actions
          uses: Azure/pipelines@v1
          with: 
           azure-devops-project-url: 'https://dev.azure.com/rvmado/NVS_EH'
           azure-pipeline-name: 'Application03'
           azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
         # runs:
          #  using: 'node20'
          #  main: 'main.js'
